#source COMPILE.csh
source COMPILE_dist_init.csh
#source COMPILE_dist_init_ng.csh
source COMPILE_mhd_init.csh
source COMPILE_cubep3m.csh
source COMPILE_cic_power.csh
source COMPILE_cic_power_mhd.csh 
#source COMPILE_cic_velpower.csh
#source COMPILE_cic_velpower_mhd.csh
